version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-ai-api-dev
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app  
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
